src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?float $surface = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\Column]
    private ?int $bedrooms = null;

    #[ORM\Column(length: 255)]
    private ?string $energyClass = null;

    #[ORM\Column]
    private ?bool $isPublished = null;

    #[ORM\Column]
    private ?DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $updatedAt = null;

    /**
     * @var Collection<int, Photo>
     */
    #[ORM\OneToMany(targetEntity: Photo::class, mappedBy: 'property')]
    private Collection $photos;

    /**
     * @var Collection<int, Lead>
     */
    #[ORM\OneToMany(targetEntity: Lead::class, mappedBy: 'property')]
    private Collection $leads;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'favorite')]
    private Collection $favorite;

    #[ORM\Column(length: 255)]
    private ?string $town = null;

    #[ORM\Column(length: 255)]
    private ?string $main_photo = null;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->leads = new ArrayCollection();
        $this->favorite = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): static
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): static
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): static
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getEnergyClass(): ?string
    {
        return $this->energyClass;
    }

    public function setEnergyClass(string $energyClass): static
    {
        $this->energyClass = $energyClass;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): static
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt ?? new DateTimeImmutable();

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): static
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setProperty($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): static
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getProperty() === $this) {
                $photo->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Lead>
     */
    public function getLeads(): Collection
    {
        return $this->leads;
    }

    public function addLead(Lead $lead): static
    {
        if (!$this->leads->contains($lead)) {
            $this->leads->add($lead);
            $lead->setProperty($this);
        }

        return $this;
    }

    public function removeLead(Lead $lead): static
    {
        if ($this->leads->removeElement($lead)) {
            // set the owning side to null (unless already changed)
            if ($lead->getProperty() === $this) {
                $lead->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFavorite(): Collection
    {
        return $this->favorite;
    }

    public function addFavorite(User $favorite): static
    {
        if (!$this->favorite->contains($favorite)) {
            $this->favorite->add($favorite);
            $favorite->addFavorite($this);
        }

        return $this;
    }

    public function removefavorite(User $favorite): static
    {
        if ($this->favorite->removeElement($favorite)) {
            $favorite->removeFavorite($this);
        }

        return $this;
    }

    public function __tostring()
    {
        return $this->title;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): static
    {
        $this->town = $town;

        return $this;
    }

    public function getMainPhoto(): ?string
    {
        return $this->main_photo;
    }

    public function setMainPhoto(string $main_photo): static
    {
        $this->main_photo = $main_photo;

        return $this;
    }
}

src/Controller/ListController.php
<?php

namespace App\Controller;

use App\Form\FilterType;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class ListController extends AbstractController
{
    #[Route('/list', name: 'app_list')]
    public function index(PropertyRepository $propertyRepository): Response
    {
        $items = $propertyRepository->findAll();

        $filter = $this->createForm(FilterType::class);

        if ($filter->isSubmitted() && $filter->isValid()) {
            dd('oui');
        }
        return $this->render('list/index.html.twig', [
            'controller_name' => 'ListController',
            'items' => $items,
            'form' => $filter
        ]);
    }
}

templates/list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ListController!
{% endblock %}

{% block body %}

	<nav id="header-nav">
		<div>
			<i class="fa-solid fa-house"></i>
			<h2>
				ImmoLite
			</h2>
		</div>
		<ul>
			<li>
				<a href="{{path('app_home')}}" style="{% if app.request.attributes.get('_route') == "app_home" %} background: red; color: white; {% endif %}">Accueil</a>
			</li>
			<li>
				<a href="{{path('app_list')}}" style="{% if app.request.attributes.get('_route') == "app_liste" %} background: red; color: white; {% endif %}">Liste</a>
			</li>
			<li>
				<a href="" style="{% if app.request.attributes.get('_route') == "app_fiche" %} background: red; color: white; {% endif %}">Fiche</a>
			</li>
			{% if is_granted('ROLE_ADMIN')
                %}
				<li>
					<a href="">Admin</a>
				</li>
			{% endif %}
		</ul>
		<ul>
			<li><a href="{{path('app_login')}}">Se Connecter</a></li>
			<li><a href="{{path('app_register')}}">S'inscrire</a></li>
		</ul>
	</nav>

	<section id="section-list">
		<div id="filter-list">
			<h2>
				Filtres
			</h2>
			{{form_start(form)}}
			{{form_row(form.type)}}
			<div>
				{{form_row(form.priceMin)}}
				{{form_row(form.priceMax)}}
			</div>
			<div>
				{{form_row(form.surfaceMin)}}
				{{form_row(form.surfaceMax)}}
			</div>
			<div>
				{{form_row(form.roomsMin)}}
				{{form_row(form.roomsMax)}}
			</div>
			<div>
				{{form_row(form.bedroomsMin)}}
				{{form_row(form.bedroomsMax)}}
			</div>
			{{form_row(form.energyClass)}}
			{{form_row(form.town)}}
			<div>
				{{form_end(form)}}
			</div>
		</div>
		<div id="property-list">
			{% for item in items %}
				<div id="item-list">
					<div style="background-image : url('{{asset('images/annonces/'~ (item.mainPhoto ? item.mainPhoto : 'indisponible.webp'))}}')" id="troisDerAnnonce">
						<div id="type-dpe-fav">
							<div>
								<span id="type">{{item.type}}</span>
								<span id="energy">DPE :
									{{item.energyClass}}</span>
							</div>
							<span id="favorite">
								<i class="fa-solid fa-heart" style="color: #e60f24;"></i>
							</span>
						</div>
						<p id="troisDerPrice">{{item.price|number_format(2, ',', ' ')}}
							€</p>
					</div>
					<div id="troisDerTexte">
						<h4>{{item.title}}</h4>
						<div id="troisDerDescr">
							<p>{{item.town}}</p>
							<p>{{item.surface}}
								m².</p>
							<p>{{item.rooms}}
								p.</p>
							<p>
								{{item.bedrooms}}
								ch.</p>
						</div>
						<div>
							<p>
								<a href="">Voir la fiche</a>
							</p>
							<button id="contact" class="redButton">
								Contacter
							</button>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</section>
{% endblock %}